packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - livekit-client@2.22.0
