#!/usr/bin/env bash
# Deploy the SFU + Redis onto raven-sfu-01.
#
# Secrets are read from Key Vault at deploy time and written to
# /opt/raven/.env on the VM with mode 600, root-owned. They are never
# printed, never committed, and never baked into the image.
#
# Hardening left for later: give the VM a managed identity with
# Key Vault Secrets User and have it fetch its own secrets on boot, so the
# operator's workstation is not in the path at all.
set -euo pipefail
source "$(dirname "$0")/00-variables.sh"

SSH_OPTS=(-i "${RAVEN_SSH_KEY}" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=20)
SFU_PUBLIC_IP="$(az network public-ip show -g "${RAVEN_RG}" -n "${RAVEN_SFU_IP_NAME}" --query ipAddress -o tsv)"
SFU_PRIVATE_IP="$(az vm show -g "${RAVEN_RG}" -n "${RAVEN_SFU_VM}" -d --query privateIps -o tsv)"
LOGIN_SERVER="$(az acr show -n "${RAVEN_ACR}" -g "${RAVEN_RG}" --query loginServer -o tsv)"
# Same tag source as 04-images.sh; see 00-variables.sh.
TAG="${RAVEN_IMAGE_TAG}"

echo "==> Target ${RAVEN_SFU_VM}  public=${SFU_PUBLIC_IP}  private=${SFU_PRIVATE_IP}"

kv() { az keyvault secret show --vault-name "${RAVEN_KV}" -n "$1" --query value -o tsv; }

# Registration goes over the Container App's public HTTPS ingress. The
# secret travels as a bearer token on an encrypted connection; there is no
# in-VNet ingress address for an externally-exposed Container App.
API_FQDN="$(az containerapp show -n "${RAVEN_API_APP:-raven-api}" -g "${RAVEN_RG}" \
  --query properties.configuration.ingress.fqdn -o tsv 2>/dev/null || true)"
if [ -n "${API_FQDN}" ]; then
  SFU_CONTROL_PLANE_LINE="SFU_CONTROL_PLANE_URL=https://${API_FQDN}"
  echo "==> Control plane: https://${API_FQDN}"
else
  SFU_CONTROL_PLANE_LINE="# SFU_CONTROL_PLANE_URL unset — no Container App found"
  echo "==> No Container App found; SFU will retry registration until Phase 3 deploys one"
fi
ACR_USER="$(az acr credential show -n "${RAVEN_ACR}" --query username -o tsv)"
ACR_PASS="$(az acr credential show -n "${RAVEN_ACR}" --query 'passwords[0].value' -o tsv)"

# ---------------------------------------------------------------------------
# compose file — generated locally, copied over, never holds a secret
# ---------------------------------------------------------------------------
COMPOSE=$(cat <<YAML
# Livqeno media plane — generated by infrastructure/azure/06-deploy-sfu.sh.
# Do not edit on the VM; edit the script and re-run.
services:
  redis:
    image: redis:7-alpine
    container_name: raven-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "\${REDIS_PASSWORD}", "--appendonly", "yes"]
    # Bound to the private NIC only, never 0.0.0.0. The NSG already blocks
    # 6379 from the Internet; this is the second lock on the same door, so a
    # future NSG mistake does not expose Redis on its own.
    ports:
      - "${SFU_PRIVATE_IP}:6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "\${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  sfu:
    image: ${LOGIN_SERVER}/raven-sfu:${TAG}
    container_name: raven-sfu
    restart: unless-stopped
    # host networking, not published ports: ICE binds 201 UDP sockets and
    # advertises the exact port it bound. Routing those through docker's
    # userland proxy would add a hop per flow for no benefit, and any
    # port remapping would hand clients addresses that do not exist
    # (docs/rtc/networking.md).
    network_mode: host
    env_file: /opt/raven/.env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
YAML
)

# ---------------------------------------------------------------------------
# env file — secrets, mode 600
# ---------------------------------------------------------------------------
ENVFILE=$(cat <<ENV
# Generated by infrastructure/azure/06-deploy-sfu.sh. Mode 600.
REDIS_PASSWORD=$(kv redis-password)

SFU_NODE_ID=sfu-${RAVEN_LOCATION}-01
SFU_REGION=${RAVEN_LOCATION}
SFU_HTTP_ADDR=:${RAVEN_SFU_HTTP_PORT}

# The address that goes into every ICE candidate. MUST be the static public
# IP: an Azure VM never sees its public address on the NIC (it is 1:1
# NAT'd), so without this the node advertises ${SFU_PRIVATE_IP} and the only
# calls that connect are the ones that fall back to TURN — which works, and
# bills relay bandwidth for 100% of traffic.
SFU_PUBLIC_IP=${SFU_PUBLIC_IP}
# What the registry records for operators. An IP until a real hostname
# exists; no domain has been invented for it.
SFU_PUBLIC_HOST=${SFU_PUBLIC_IP}
# The address the control plane calls back on — private, in-VNet.
SFU_INTERNAL_URL=http://${SFU_PRIVATE_IP}:${RAVEN_SFU_HTTP_PORT}

# The control plane this node registers and heartbeats with. Looked up from
# the deployed Container App, so this script stays correct across redeploys.
#
# If the app does not exist yet the line is omitted and the SFU falls back to
# its :4000 default, logging "registration failed, retrying" on a backoff.
# That is expected in that state, not a fault — /healthz stays 200 because
# liveness deliberately does not depend on the link
# (services/sfu/cmd/sfu/main.go), so the node is restart-safe while waiting.
${SFU_CONTROL_PLANE_LINE}
SFU_REGISTRATION_SECRET=$(kv sfu-registration-secret)

SFU_UDP_PORT_MIN=${RAVEN_SFU_UDP_MIN}
SFU_UDP_PORT_MAX=${RAVEN_SFU_UDP_MAX}
SFU_ROOM_CAPACITY=100
SFU_HEARTBEAT_INTERVAL_SECONDS=10
SFU_LOG_LEVEL=info
ENV
)

echo "==> Writing /opt/raven on ${SFU_PUBLIC_IP}"
ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${SFU_PUBLIC_IP}" \
  "sudo mkdir -p /opt/raven && sudo chown ${RAVEN_ADMIN_USER}:${RAVEN_ADMIN_USER} /opt/raven"

printf '%s\n' "${COMPOSE}" | ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${SFU_PUBLIC_IP}" \
  "cat > /opt/raven/docker-compose.yml"
printf '%s\n' "${ENVFILE}" | ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${SFU_PUBLIC_IP}" \
  "umask 077 && cat > /opt/raven/.env && chmod 600 /opt/raven/.env"

# `docker login` writes the credential to the *invoking user's*
# ~/.docker/config.json. Logging in only as ${RAVEN_ADMIN_USER} therefore
# leaves root with no credential at all, and every pull that runs as root —
# `sudo docker compose pull`, a systemd unit, or `az vm run-command`, which
# is the usual fallback when raven-sfu-nsg's SSH allowlist does not include
# your current address — fails with:
#
#   error from registry: authentication required, visit https://aka.ms/acr/authorization
#
# That message reads like a broken registry, an expired token or a disabled
# admin user, and is none of those: the image is there, the admin
# credential is valid, and the same pull succeeds as ${RAVEN_ADMIN_USER}.
# Both users get the credential so the failure cannot recur.
#
# The password travels on ssh's stdin rather than inside the remote command
# string. A command string is visible in the VM's process table while it
# runs, and in this shell's own argv.
echo "==> Logging in to ACR as ${RAVEN_ADMIN_USER}"
printf '%s' "${ACR_PASS}" | ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${SFU_PUBLIC_IP}" \
  "docker login ${LOGIN_SERVER} -u '${ACR_USER}' --password-stdin >/dev/null"

echo "==> Logging in to ACR as root (sudo is NOPASSWD on this VM)"
printf '%s' "${ACR_PASS}" | ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${SFU_PUBLIC_IP}" \
  "sudo -n docker login ${LOGIN_SERVER} -u '${ACR_USER}' --password-stdin >/dev/null"

echo "==> Pulling ${LOGIN_SERVER}/raven-sfu:${TAG} and starting"
ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${SFU_PUBLIC_IP}" \
  "cd /opt/raven \
   && docker compose --env-file .env pull -q \
   && docker compose --env-file .env up -d"

echo "==> Containers"
ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${SFU_PUBLIC_IP}" \
  "docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Image}}'"
