#!/usr/bin/env bash
# Deploy coturn onto raven-coturn-01.
#
# TLS is not set up by this script — it brings up plain STUN/TURN on 3478
# only, which clients can use immediately. Run 11-turn-tls.sh afterward to
# add TURNS/DTLS on 5349 with a real certificate (see the block at the end
# of this file for what that does).
set -euo pipefail
source "$(dirname "$0")/00-variables.sh"

SSH_OPTS=(-i "${RAVEN_SSH_KEY}" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=20)
TURN_PUBLIC_IP="$(az network public-ip show -g "${RAVEN_RG}" -n "${RAVEN_TURN_IP_NAME}" --query ipAddress -o tsv)"
TURN_PRIVATE_IP="$(az vm show -g "${RAVEN_RG}" -n "${RAVEN_TURN_VM}" -d --query privateIps -o tsv)"

echo "==> Target ${RAVEN_TURN_VM}  public=${TURN_PUBLIC_IP}  private=${TURN_PRIVATE_IP}"

TURN_SECRET="$(az keyvault secret show --vault-name "${RAVEN_KV}" -n turn-secret --query value -o tsv)"

# The realm. An IP for now — item: no production hostname has been decided,
# and inventing one would produce a config that silently fails auth the day
# a real domain arrives (the realm is part of the credential hash).
TURN_REALM="${RAVEN_TURN_REALM:-${TURN_PUBLIC_IP}}"

CONF=$(cat <<CONFIG
# Livqeno coturn — generated by infrastructure/azure/07-deploy-coturn.sh.
# Mirrors infrastructure/docker/coturn/turnserver.conf, adapted for Azure.

listening-port=${RAVEN_TURN_PORT}

# Relay range. Must match the NSG rule AllowTurnRelayUdp and the repo's
# turnserver.conf. coturn allocates a relay address from here per
# allocation and the peer side sends to it.
min-port=${RAVEN_TURN_RELAY_MIN}
max-port=${RAVEN_TURN_RELAY_MAX}

# The single most important line for a cloud deployment. An Azure VM never
# sees its public address on the NIC — it is 1:1 NAT'd — so without this
# coturn hands out relay candidates pointing at ${TURN_PRIVATE_IP}, which no
# client can reach. Same failure class as a wrong SFU_PUBLIC_IP: the
# allocation succeeds and the media silently never arrives.
external-ip=${TURN_PUBLIC_IP}/${TURN_PRIVATE_IP}

# Ephemeral credentials. Livqeno mints username="<expiry>:<identity>" and
# credential=base64(HMAC-SHA1(secret, username)) per token
# (apps/api/src/modules/rtc-tokens/turn-credential.util.ts); coturn
# recomputes the same hash to authorize. There is no user database and no
# API->coturn control channel — the shared secret IS the coupling.
use-auth-secret
static-auth-secret=${TURN_SECRET}
realm=${TURN_REALM}

fingerprint
no-multicast-peers
# Nothing behind this relay should be reachable via it.
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
# ...except the SFU, which is a legitimate peer for relayed media.
allowed-peer-ip=${RAVEN_SUBNET_MEDIA_CIDR%/*}-10.10.1.255

# No TLS listener: no certificate. Advertising a TURNS URI that fails the
# handshake is worse than not advertising it — the client burns an ICE
# candidate on a path that cannot work.
no-tls
no-dtls

# Quotas, from .env.example's local defaults.
user-quota=${RAVEN_TURN_USER_QUOTA:-10}
total-quota=${RAVEN_TURN_TOTAL_QUOTA:-400}
max-bps=${RAVEN_TURN_MAX_BPS:-1000000}

simple-log
log-file=stdout
verbose
# No CLI listener; nothing needs to reconfigure this at runtime.
no-cli
CONFIG
)

COMPOSE=$(cat <<YAML
# Livqeno TURN — generated by infrastructure/azure/07-deploy-coturn.sh.
services:
  coturn:
    image: coturn/coturn:4.17.2
    container_name: raven-coturn
    restart: unless-stopped
    # host networking: 3478 plus a 41-port relay range, and coturn needs to
    # see real source addresses to build correct candidates.
    network_mode: host
    volumes:
      - /opt/raven/turnserver.conf:/etc/turnserver.conf:ro
    command: ["-c", "/etc/turnserver.conf"]
YAML
)

echo "==> Writing /opt/raven on ${TURN_PUBLIC_IP}"
ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" \
  "sudo mkdir -p /opt/raven && sudo chown ${RAVEN_ADMIN_USER}:${RAVEN_ADMIN_USER} /opt/raven"

# The conf carries static-auth-secret, so it stays mode 600 — but it must be
# owned by the uid the container runs as (nobody:nogroup, 65534). coturn does
# NOT fail when it cannot read its config file: it logs a warning and
# continues with defaults, which means no realm and NO AUTHENTICATION — an
# open relay that anyone on the Internet can allocate through. A 600 file
# owned by the SSH user reproduces exactly that. The assertion at the end of
# this script exists because of it.
printf '%s\n' "${CONF}" | ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" \
  "umask 077 && cat > /opt/raven/turnserver.conf \
   && sudo chown 65534:65534 /opt/raven/turnserver.conf \
   && sudo chmod 600 /opt/raven/turnserver.conf"
printf '%s\n' "${COMPOSE}" | ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" \
  "cat > /opt/raven/docker-compose.yml"

echo "==> Starting coturn"
ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" \
  "cd /opt/raven && docker compose pull -q && docker compose up -d --force-recreate && sleep 6 && docker ps --format 'table {{.Names}}\t{{.Status}}'"

# ---------------------------------------------------------------------------
# Assert the config was actually loaded.
#
# Non-negotiable: an unreadable config file leaves coturn running as an open
# relay rather than dead, so "the container is up" proves nothing. Two checks:
# the realm we set must appear in the log, and an Allocate with no credential
# must be refused with 401.
# ---------------------------------------------------------------------------
echo "==> Verifying the config took effect"
if ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" \
     "docker logs raven-coturn 2>&1 | grep -q 'Default realm: ${TURN_REALM}'"; then
  echo "    realm ${TURN_REALM} loaded"
else
  echo "    FAIL: coturn did not load ${TURN_REALM} as its realm."
  echo "    It is probably running on defaults with NO AUTH. Check that"
  echo "    /opt/raven/turnserver.conf is readable by uid 65534."
  ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" "cd /opt/raven && docker compose stop"
  echo "    coturn stopped so it is not left exposed."
  exit 1
fi

# ---------------------------------------------------------------------------
# TLS — handled by 11-turn-tls.sh, not a manual step
# ---------------------------------------------------------------------------
# It gets a certificate (Azure's own DNS label on this VM's static IP, so no
# custom hostname is needed), rewrites this conf with tls-listening-port /
# cert / pkey, opens the NSG rule for TURN_TLS_PORT, and points the realm at
# the hostname. 13-api-app.sh then sets TURN_HOST and TURN_TLS_PORT on the
# API — both required in production (env.validation.ts), and TURN_HOST must
# not be "localhost".
