#!/usr/bin/env bash
# Enable TURNS (TURN over TLS) on coturn with a real certificate.
#
# The hostname is Azure's own DNS label on the coturn static IP —
# <label>.<region>.cloudapp.azure.com. It is a genuine name the subscription
# owns, resolvable publicly, and Let's Encrypt issues for it. No domain was
# registered and no certificate is self-signed. Swap in a custom domain
# later by re-running with RAVEN_TURN_FQDN set.
#
# Why this matters beyond TURNS itself: apps/api refuses to boot with
# NODE_ENV=production unless TURN_TLS_PORT is set
# (shared/config/env.validation.ts). Setting that variable without a working
# listener would satisfy the check while handing clients a turns: URI that
# fails its handshake — so the listener is made real first.
set -euo pipefail
source "$(dirname "$0")/00-variables.sh"

SSH_OPTS=(-i "${RAVEN_SSH_KEY}" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=20)
TURN_PUBLIC_IP="$(az network public-ip show -g "${RAVEN_RG}" -n "${RAVEN_TURN_IP_NAME}" --query ipAddress -o tsv)"
TURN_PRIVATE_IP="$(az vm show -g "${RAVEN_RG}" -n "${RAVEN_TURN_VM}" -d --query privateIps -o tsv)"
FQDN="${RAVEN_TURN_FQDN:-$(az network public-ip show -g "${RAVEN_RG}" -n "${RAVEN_TURN_IP_NAME}" --query dnsSettings.fqdn -o tsv)}"
ACME_EMAIL="${RAVEN_ACME_EMAIL:-}"

echo "==> TURN hostname: ${FQDN} -> ${TURN_PUBLIC_IP}"

# HTTP-01 needs port 80 reachable. Left open afterwards so unattended
# renewal works; coturn serves nothing on 80, and certbot only binds it for
# the seconds a challenge takes.
echo "==> Opening 80/tcp for the ACME challenge"
az network nsg rule create -g "${RAVEN_RG}" --nsg-name "${RAVEN_TURN_NSG}" \
  -n AllowAcmeHttp --priority 130 --direction Inbound --access Allow \
  --protocol Tcp --source-address-prefixes Internet --destination-port-ranges 80 \
  --description "ACME HTTP-01 for the TURN certificate. certbot standalone; nothing else serves 80." \
  --output none 2>/dev/null || echo "    rule exists"

echo "==> Issuing certificate"
ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" "
  set -e
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq certbot >/dev/null
  if sudo test -d /etc/letsencrypt/live/${FQDN}; then
    echo '    certificate already present'
  else
    sudo certbot certonly --standalone --non-interactive --agree-tos \
      ${ACME_EMAIL:+--email ${ACME_EMAIL}} ${ACME_EMAIL:---register-unsafely-without-email} \
      -d ${FQDN}
  fi
"

# coturn runs as nobody:nogroup (65534) and cannot read /etc/letsencrypt's
# root-owned private key. Copy into place with that ownership, and re-copy
# on every renewal via a deploy hook — otherwise TLS silently keeps serving
# an expired cert after the first renewal.
echo "==> Staging certs for uid 65534 + installing renewal hook"
ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" "
  set -e
  sudo mkdir -p /opt/raven/certs
  sudo install -o 65534 -g 65534 -m 644 /etc/letsencrypt/live/${FQDN}/fullchain.pem /opt/raven/certs/fullchain.pem
  sudo install -o 65534 -g 65534 -m 600 /etc/letsencrypt/live/${FQDN}/privkey.pem   /opt/raven/certs/privkey.pem
  sudo tee /etc/letsencrypt/renewal-hooks/deploy/raven-coturn.sh >/dev/null <<'HOOK'
#!/bin/sh
# Re-stage the renewed cert with the ownership coturn needs, then restart it.
set -e
FQDN_DIR=\$(ls -d /etc/letsencrypt/live/*/ | head -1)
install -o 65534 -g 65534 -m 644 \"\${FQDN_DIR}fullchain.pem\" /opt/raven/certs/fullchain.pem
install -o 65534 -g 65534 -m 600 \"\${FQDN_DIR}privkey.pem\"   /opt/raven/certs/privkey.pem
cd /opt/raven && docker compose restart coturn
HOOK
  sudo chmod +x /etc/letsencrypt/renewal-hooks/deploy/raven-coturn.sh
  echo '    hook installed'
"

echo "==> Rewriting turnserver.conf with TLS enabled"
TURN_SECRET="$(az keyvault secret show --vault-name "${RAVEN_KV}" -n turn-secret --query value -o tsv)"

CONF=$(cat <<CONFIG
# Livqeno coturn — generated by infrastructure/azure/11-turn-tls.sh.
listening-port=${RAVEN_TURN_PORT}
tls-listening-port=${RAVEN_TURN_TLS_PORT}

min-port=${RAVEN_TURN_RELAY_MIN}
max-port=${RAVEN_TURN_RELAY_MAX}

# Azure 1:1 NATs the public address; without this coturn hands out relay
# candidates on the private NIC and media silently never arrives.
external-ip=${TURN_PUBLIC_IP}/${TURN_PRIVATE_IP}

cert=/etc/coturn/certs/fullchain.pem
pkey=/etc/coturn/certs/privkey.pem

# Ephemeral credentials, HMAC-SHA1 over "<expiry>:<identity>" with the
# shared secret. Livqeno mints them in
# apps/api/src/modules/rtc-tokens/turn-credential.util.ts; coturn recomputes
# the same hash. No user database, no API->coturn control channel.
use-auth-secret
static-auth-secret=${TURN_SECRET}
# The realm is the hostname now, not the bare IP.
realm=${FQDN}

fingerprint
no-multicast-peers
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
allowed-peer-ip=10.10.1.0-10.10.1.255

user-quota=${RAVEN_TURN_USER_QUOTA:-10}
total-quota=${RAVEN_TURN_TOTAL_QUOTA:-400}
max-bps=${RAVEN_TURN_MAX_BPS:-1000000}

simple-log
log-file=stdout
no-cli
CONFIG
)

COMPOSE=$(cat <<YAML
# Livqeno TURN — generated by infrastructure/azure/11-turn-tls.sh.
services:
  coturn:
    image: coturn/coturn:4.17.2
    container_name: raven-coturn
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/raven/turnserver.conf:/etc/turnserver.conf:ro
      - /opt/raven/certs:/etc/coturn/certs:ro
    command: ["-c", "/etc/turnserver.conf"]
YAML
)

# 600 and owned by 65534 — coturn does NOT fail when it cannot read its
# config, it runs with no auth at all. See 07-deploy-coturn.sh.
printf '%s\n' "${CONF}" | ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" \
  "umask 077 && cat > /tmp/turnserver.conf && sudo install -o 65534 -g 65534 -m 600 /tmp/turnserver.conf /opt/raven/turnserver.conf && rm -f /tmp/turnserver.conf"
printf '%s\n' "${COMPOSE}" | ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" \
  "cat > /opt/raven/docker-compose.yml"

echo "==> Opening ${RAVEN_TURN_TLS_PORT} (TURNS/DTLS)"
az network nsg rule create -g "${RAVEN_RG}" --nsg-name "${RAVEN_TURN_NSG}" \
  -n AllowTurnsTls --priority 140 --direction Inbound --access Allow \
  --protocol '*' --source-address-prefixes Internet \
  --destination-port-ranges "${RAVEN_TURN_TLS_PORT}" \
  --description "TURNS over TCP + TURN/DTLS over UDP." --output none 2>/dev/null || echo "    rule exists"

echo "==> Restarting coturn"
ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" \
  "cd /opt/raven && docker compose up -d --force-recreate && sleep 6"

echo "==> Asserting config + TLS listener"
if ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" \
     "docker logs raven-coturn 2>&1 | grep -q 'Default realm: ${FQDN}'"; then
  echo "    realm ${FQDN} loaded"
else
  echo "    FAIL: config not loaded — coturn may be running with NO AUTH."
  ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" "cd /opt/raven && docker compose stop"
  exit 1
fi
ssh "${SSH_OPTS[@]}" "${RAVEN_ADMIN_USER}@${TURN_PUBLIC_IP}" \
  "docker logs raven-coturn 2>&1 | grep -iE 'tls|dtls' | head -5"

echo
echo "TURN_HOST=${FQDN}"
echo "TURN_TLS_PORT=${RAVEN_TURN_TLS_PORT}"
