WARNING: The behavior of this command has been altered by the following extension: containerapp
id: /subscriptions/9f529403-0a2d-4008-b35e-41c7f2a13c7a/resourceGroups/flanca-rg/providers/Microsoft.App/managedEnvironments/flanca-env
location: Central India
name: flanca-env
properties:
  appInsightsConfiguration: null
  appLogsConfiguration:
    destination: log-analytics
    logAnalyticsConfiguration:
      customerId: fbb02dd3-b0c3-4b8d-a9ed-a42daee363cb
      dynamicJsonColumns: false
      sharedKey: null
  availabilityZones: null
  customDomainConfiguration:
    certificateKeyVaultProperties: null
    certificatePassword: null
    certificateValue: null
    customDomainVerificationId: 2E961EE1E48C8CE8208662295EE842FDD5541FEB7DB6B382117A83D449B79BCF
    dnsSuffix: null
    expirationDate: null
    subjectName: null
    thumbprint: null
  daprAIConnectionString: null
  daprAIInstrumentationKey: null
  daprConfiguration:
    version: 1.16.4-msft.12
  defaultDomain: proudstone-deb2fdad.centralindia.azurecontainerapps.io
  diskEncryptionConfiguration: null
  environmentMode: WorkloadProfiles
  eventStreamEndpoint: https://centralindia.azurecontainerapps.dev/subscriptions/9f529403-0a2d-4008-b35e-41c7f2a13c7a/resourceGroups/flanca-rg/managedEnvironments/flanca-env/eventstream
  infrastructureResourceGroup: null
  ingressConfiguration: null
  kedaConfiguration:
    version: 2.18.1
  openTelemetryConfiguration: null
  peerAuthentication:
    mtls:
      enabled: false
  peerTrafficConfiguration:
    encryption:
      enabled: false
  provisioningState: Succeeded
  publicNetworkAccess: Enabled
  staticIp: 4.186.52.57
  vnetConfiguration: null
  workloadProfiles:
  - enableFips: false
    name: Consumption
    workloadProfileType: Consumption
  zoneRedundant: false
resourceGroup: flanca-rg
systemData:
  createdAt: '2026-09-02T10:56:49.7519765'
  createdBy: atul.12320766@lpu.in
  createdByType: User
  lastModifiedAt: '2026-09-02T10:56:49.7519765'
  lastModifiedBy: atul.12320766@lpu.in
  lastModifiedByType: User
type: Microsoft.App/managedEnvironments
