#!/usr/bin/env bash
# Generates a self-signed TLS cert for coturn's local TURNS/DTLS listener.
#
# Not for production — browsers reject self-signed certs for TURNS by
# default, and production needs a real CA-issued cert (e.g. Let's Encrypt)
# for the public TURN hostname. This just lets us exercise the TLS
# server-side config locally. See docs/turn.md#tls.
#
# Usage: bash scripts/generate-turn-cert.sh
set -euo pipefail

cd "$(dirname "$0")/.."
CERT_DIR="infrastructure/docker/coturn/certs"
mkdir -p "$CERT_DIR"

if [ -f "$CERT_DIR/cert.pem" ] && [ -f "$CERT_DIR/key.pem" ]; then
  echo "Certificate already exists at $CERT_DIR — skipping. Delete it first to regenerate."
else
  openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "$CERT_DIR/key.pem" \
    -out "$CERT_DIR/cert.pem" \
    -days 365 \
    -subj "/CN=localhost" \
    -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"
  echo "Generated self-signed cert: $CERT_DIR/cert.pem / key.pem (365 days, CN=localhost)"
fi

# Readable by group/other, not just the user who generated it. The
# coturn image drops privileges to nobody (uid 65534) and reads the key
# through a read-only bind mount, so a 600 key owned by the generating
# user — the developer, or the CI runner — is a key coturn cannot open.
# It does not fail loudly when that happens: turnserver logs "cannot find
# private key file", disables the TLS *and* DTLS listeners, and keeps
# serving plain STUN/TURN on 3478, so 5349 is quietly dead.
#
# Safe only because of what this key is: a throwaway self-signed cert for
# a local listener, regenerated on demand and gitignored. A production
# TURN key belongs in a secret store, not on a bind mount.
#
# Applied outside the branch above so that certs generated by an older
# version of this script get repaired too, rather than staying at 600 and
# silently keeping TURNS down.
chmod 644 "$CERT_DIR/key.pem"
chmod 644 "$CERT_DIR/cert.pem"
